[custom.all.cyby-draw]
type    = "local"
path    = "."
ipkg    = "cyby-draw.ipkg"

[custom.all.cyby-draw-app]
type    = "local"
path    = "app"
ipkg    = "cyby-draw-app.ipkg"

[custom.all.cyby-draw-word-addin]
type    = "local"
path    = "word-addin"
ipkg    = "cyby-draw-word-addin.ipkg"

[custom.all.cyby-css]
type    = "local"
path    = "cyby-css"
ipkg    = "cyby-css.ipkg"

[custom.all]
http-types.commit      = "latest:main"
http-client-api.commit = "latest:main"
async-dom.commit       = "latest:log_events"
chem-generators.commit = "latest:main"
chem.commit            = "latest:main"
css.commit             = "latest:main"
ilex-json.commit       = "latest:main"
ilex.commit            = "latest:main"
indexed-graph.commit   = "latest:main"
ref1.commit            = "latest:main"
