||| This module takes care of all events used for the word add-in (extension)
module CyBy.Draw.Word

import Web.MVC
import Data.String
import Derive.Prelude
import CyBy.Draw
import CyBy.Draw.Word.DomBindings
import CyBy.Draw.Word.PromiseMonad

%default total
%language ElabReflection

--------------------------------------------------------------------------------
-- Debugging
--------------------------------------------------------------------------------

data Level = Trace | Debug | Info | Silence

%runElab derive "Level" [Show,Eq,Ord]

export
record LogLevel where
  [noHints]
  constructor L
  lvl : Level

failing "Can't find an implementation for LogLevel"
  testLogLevel : LogLevel
  testLogLevel = %search

export
lvlDebug : LogLevel 
lvlDebug = L Debug

export
lvlTrace : LogLevel 
lvlTrace = L Trace

export
lvlInfo : LogLevel 
lvlInfo = L Info

export
lvlSilence : LogLevel 
lvlSilence = L Silence

export
log : HasIO io => (d : LogLevel) => Level -> Lazy String -> io ()
log lvl msg = when (lvl >= d.lvl) (putStrLn msg)

export
trace : HasIO io => (d : LogLevel) => Lazy String -> io ()
trace = log Trace

export
debug : HasIO io => (d : LogLevel) => Lazy String -> io ()
debug = log Debug

export
info : HasIO io => (d : LogLevel) => Lazy String -> io ()
info = log Info

--------------------------------------------------------------------------------
-- Export / Import Structures
--------------------------------------------------------------------------------

-- A quick note on the mechanism used in this module:
-- As Word is based on XML structure, its JavaScript API
-- allows it to be extracted as a string. Therefore,
-- information about the structure is saved inside certain
-- XML nodes.
-- To export a new structure from CyBy-Draw to Word, the
-- JS API offers a simple image insertion function that
-- generates the required nodes. To retrieve the structure
-- at a later time, the MOL graph is stored in a metadata
-- node in the SVG. However, if a structure (generated by
-- the CyBy-Draw add-in) is to be modified, the entire SVG
-- node must be replaced using the JS string function
-- replace. As the size of the new SVG may differ, the old
-- Word-generated values must be replaced. Currently, new
-- size values are generated by inserting a temporary image
-- and extracting the values from the XML. The temporary
-- image is then deleted.
-- To retrieve a structure from Word, the cursor selection
-- XML string can be searched for the first occurrence of
-- the SVG node and its first attribute, 'xmlns'. As Word
-- always adds a 'viewBox' attribute and places it as the
-- first attribute of an SVG node, only the current
-- selection of SVGs generated by CyBy-Draw are searched
-- for. As the RegEx is non-greedy, only the first SVG
-- occurrence is relevant.

-- As word uses EMU's (English Metric Units) as image sizes,
-- a conversion from pixels to EUM's had to be done.
-- 1 Inch = 914400 EMU
-- 1 Inch = 96 px (as Microsoft uses 96 ppi as standard)
-- EMU = (914400 / 96) * px = 9525 * px
-- As EMU should be an Integer the Nat type is used here.
-- The difference of the floor rounding is (I think)
-- negligible.
record EMU where
  constructor E
  value : Nat

pxToEMU : (px : Double) -> EMU
pxToEMU = E . cast . (* 9525)

emuAsStr : EMU -> String
emuAsStr = cast . value

exportImgEmptSel :
     {auto _ : LogLevel}
  -> Context
  -> Selection
  -> (svg : String)
  -> (width,height : String)
  -> Prog ()
exportImgEmptSel c s svg w h = do
  debug "Selection is empty or no svg is present for replacing the structure"
  -- encode and insert the image to Word
  -- the JS API creates an xml entry, where the graph is stored
  -- in the svg reference for later use
  ignore $ insertInlinePictureFromB64 s (btoa svg)

  selOoxml <- getSelectionOoxml c s
  let idSel := extractImageIdWordSel selOoxml

  debug "New width: \{w}, new height: \{h}"

  -- replace the size of the Word generated values with the
  -- newly calculated values
  replaceOoxml s (replaceSvgAndSize selOoxml svg idSel (w,h))
  debug "exportImage succcesfull"

exportImage : LogLevel => (svg : String) -> Prog ()
exportImage svg =
  wordRun $ \c => do
    debug "Begin of function `exportImage`"
    -- replace the selected svg (or the first in the selection)
    -- with the updated structure and adjust the size accordingly
    -- if an svg is selected
    -- if the selection is empty or does not include an svg,
    -- insert the new structure after the selection / cursor
    s <- getSelection c

    -- extract the image sizes from the svg in pixels (in a
    -- string representation)
    case extractSvgSize svg of
      Nothing => do
        debug "Failed to extract the size of the svg image."
        debug "Abort inserting structure."
      Just (width,height) => do
            -- convert the pixel values into EMU's
        let wEMU := emuAsStr $ pxToEMU $ cast width
            hEMU := emuAsStr $ pxToEMU $ cast height

        -- if the selection is empty, insert the svg as a new image
        False <- isEmpty s | True => exportImgEmptSel c s svg wEMU hEMU

        -- load the selection as xml
        ooxml <- getSelectionOoxml c s
        -- check if a cyby structure is present in the selection
        let True  := hasCyBySvg ooxml
              | False => exportImgEmptSel c s svg wEMU hEMU
            idSel := extractImageIdWordSel ooxml
        -- replace the first occurring svg with the updated one
        -- and replace the new sizes
        replaceOoxml s (replaceSvgAndSize ooxml svg idSel (wEMU,hEMU))
        debug "Function `exportImage` successful"

exportImageToWord : LogLevel => (svg : String) -> JSIO ()
exportImageToWord svg = runDeflt $ exportImage svg

importImageFromWord : LogLevel => (String -> PrimIO ()) -> Prog ()
importImageFromWord f =
  wordRun $ \c => do
    debug "Begin of function `importImageFromWord`"
    -- return an empty string if the selection is empty
    s <- getSelection c
    False <- isEmpty s | True => debug "Selection is empty" >> primIO (f "")

    -- load the whole selection as xml
    ooxml <- getSelectionOoxml c s

    -- extracting the MOL file directly from the xml structure
    -- of the current selection
    -- if there are several cyby-draw generated structures, the
    -- first in the selection is imported
    case extractMetadata ooxml of
      "" => debug "No MOL-File found"
      g  => debug "Function `exportImage` succcesfull" >> primIO (f g)

fromWord : LogLevel => Cmd DrawEvent
fromWord =
  C $ \h =>
    runDeflt $ importImageFromWord $ \s =>
      case readMolfileE s of
        Left e  => toPrim (runJS $ h (Msg $ ReadErr e))
        Right m => toPrim (runJS $ h (SetTempl m))

export
WordExt : (lvl : LogLevel) -> Extension
WordExt lvl =
  E
    { doExport     = \s => cmd_ $ exportImageToWord (exportSVG s)
    , doImport     = \s => fromWord
    , importButton = True
    }
