||| This module takes care of all events used for the word add-in (extension)
module CyBy.Draw.Word

import Web.MVC
import Data.String
import Derive.Prelude
import CyBy.Draw
import CyBy.Draw.Word.DomBindings
import CyBy.Draw.Word.PromiseMonad
import Geom
import Geom.Point

import Debug.Trace

%default total
%language ElabReflection

--------------------------------------------------------------------------------
-- Debugging
--------------------------------------------------------------------------------

data Level = Trace | Debug | Info | Silence

%runElab derive "Level" [Show,Eq,Ord]

export
record LogLevel where
  [noHints]
  constructor L
  lvl : Level

failing "Can't find an implementation for LogLevel"
  testLogLevel : LogLevel
  testLogLevel = %search

export
lvlDebug : LogLevel 
lvlDebug = L Debug

export
lvlTrace : LogLevel 
lvlTrace = L Trace

export
lvlInfo : LogLevel 
lvlInfo = L Info

export
lvlSilence : LogLevel 
lvlSilence = L Silence

export
log : HasIO io => (d : LogLevel) => Level -> Lazy String -> io ()
log lvl msg = when (lvl >= d.lvl) (putStrLn msg)

export
trace : HasIO io => (d : LogLevel) => Lazy String -> io ()
trace = log Trace

export
debug : HasIO io => (d : LogLevel) => Lazy String -> io ()
debug = log Debug

export
info : HasIO io => (d : LogLevel) => Lazy String -> io ()
info = log Info

--------------------------------------------------------------------------------
-- Export / Import Structures
--------------------------------------------------------------------------------

-- A quick note on the mechanism used in this module:
-- As Word is based on XML structure, its JavaScript API
-- allows it to be extracted as a string. Therefore,
-- information about the structure is saved inside certain
-- XML nodes.
-- To export a new structure from CyBy-Draw to Word, the
-- JS API offers a simple image insertion function that
-- generates the required nodes. To retrieve the structure
-- at a later time, the MOL graph is stored in a metadata
-- node in the SVG. However, if a structure (generated by
-- the CyBy-Draw add-in) is to be modified, the entire SVG
-- node must be replaced using the JS string function
-- replace. As the size of the new SVG may differ, the old
-- Word-generated values must be replaced. Currently, new
-- size values are generated by inserting a temporary image
-- and extracting the values from the XML. The temporary
-- image is then deleted.
-- To retrieve a structure from Word, the cursor selection
-- XML string can be searched for the first occurrence of
-- the SVG node and its first attribute, 'xmlns'. As Word
-- always adds a 'viewBox' attribute and places it as the
-- first attribute of an SVG node, only the current
-- selection of SVGs generated by CyBy-Draw are searched
-- for. As the RegEx is non-greedy, only the first SVG
-- occurrence is relevant.

exportImgEmptSel :
     {auto _ : LogLevel}
  -> Context
  -> Selection
  -> (svg : String)
  -> (w,h : EMU)
  -> Prog ()
exportImgEmptSel c s svg w h = do
  debug "Selection is empty or no svg is present for replacing the structure"
  -- encode and insert the image to Word
  -- the JS API creates an xml entry, where the graph is stored
  -- in the svg reference for later use
  insertInlinePicture s svg

  selOoxml <- getSelectionOoxml c s
  let idSel := extractImageIdWordSel selOoxml

  debug "New width: \{w}, new height: \{h}"

  -- replace the size of the Word generated values with the
  -- newly calculated values
  replaceOoxml s (replaceSvgAndSize selOoxml svg idSel w h)
  debug "exportImage succcesfull"

exportImage : LogLevel => (svg : String) -> (w,h : EMU) -> Prog ()
exportImage svg w h =
  wordRun $ \c => do
    debug "Begin of function `exportImage`"
    -- replace the selected svg (or the first in the selection)
    -- with the updated structure and adjust the size accordingly
    -- if an svg is selected
    -- if the selection is empty or does not include an svg,
    -- insert the new structure after the selection / cursor
    s <- getSelection c

    -- if the selection is empty, insert the svg as a new image
    False <- isEmpty s | True => exportImgEmptSel c s svg w h

    -- load the selection as xml
    ooxml <- getSelectionOoxml c s
    -- check if a cyby structure is present in the selection
    let True  := hasCyBySvg ooxml | False => exportImgEmptSel c s svg w h
        idSel := extractImageIdWordSel ooxml
    -- replace the first occurring svg with the updated one
    -- and replace the new sizes
    replaceOoxml s (replaceSvgAndSize ooxml svg idSel w h)
    debug "Function `exportImage` successful"

exportImageToWord : LogLevel => DrawSettings => DrawState -> JSIO ()
exportImageToWord s =
 let (SD w h, svg) := exportSVGPair s
  in runDeflt $ exportImage svg (cast w) (cast h)

importImageFromWord : LogLevel => (String -> PrimIO ()) -> Prog ()
importImageFromWord f =
  wordRun $ \c => do
    debug "Begin of function `importImageFromWord`"
    -- return an empty string if the selection is empty
    s <- getSelection c
    False <- isEmpty s | True => debug "Selection is empty" >> primIO (f "")

    -- load the whole selection as xml
    ooxml <- getSelectionOoxml c s

    -- extracting the MOL file directly from the xml structure
    -- of the current selection
    -- if there are several cyby-draw generated structures, the
    -- first in the selection is imported
    case extractMetadata ooxml of
      "" => debug "No MOL-File found"
      g  => debug "Function `importImageFromWord` succcesfull" >> primIO (f g)

fromWord : LogLevel => Cmd DrawEvent
fromWord =
  C $ \h =>
    runDeflt $ importImageFromWord $ \s =>
      case readMolfileE s of
        Left e  => toPrim (runJS $ h (Msg $ ReadErr e))
        Right m => toPrim (runJS $ h (SetTempl m))

export
WordExt : (lvl : LogLevel) -> Extension
WordExt lvl =
  E
    { doExport     = \s => cmd_ $ exportImageToWord s
    , doImport     = \s => fromWord
    , importButton = True
    }
