||| This module takes care of all events used for the word add-in (extension)
module CyBy.Draw.Word

import CyBy.Draw
import CyBy.Draw.Word.I18n
import Text.CSS.Class

%default total
%hide JS.ByteString.ByteString

--------------------------------------------------------------------------------
-- Export / Import Structures
--------------------------------------------------------------------------------

-- A quick note on the mechanism used in this module:
-- As Word is based on XML structure, its JavaScript API
-- allows it to be extracted as a string. Therefore,
-- information about the structure is saved inside certain
-- XML nodes.
-- To export a new structure from CyBy-Draw to Word, the
-- JS API offers a simple image insertion function that
-- generates the required nodes. To retrieve the structure
-- at a later time, the MOL graph is stored in a metadata
-- node in the SVG. However, if a structure (generated by
-- the CyBy-Draw add-in) is to be modified, the entire SVG
-- node must be replaced using the JS string function
-- replace. As the size of the new SVG may differ, the old
-- Word-generated values must be replaced. Currently, new
-- size values are generated by inserting a temporary image
-- and extracting the values from the XML. The temporary
-- image is then deleted.
-- To retrieve a structure from Word, the cursor selection
-- XML string can be searched for the first occurrence of
-- the SVG node and its first attribute, 'xmlns'. As Word
-- always adds a 'viewBox' attribute and places it as the
-- first attribute of an SVG node, only the current
-- selection of SVGs generated by CyBy-Draw are searched
-- for. As the RegEx is non-greedy, only the first SVG
-- occurrence is relevant.

parameters {auto loc : WordLocal}

  insertNew :
       Context
    -> Selection
    -> (svg : String)
    -> (w,h : EMU)
    -> Act ()
  insertNew c s svg w h = do
    emptySelection
    -- encode and insert the image to Word
    -- the JS API creates an xml entry, where the graph is stored
    -- in the svg reference for later use
    insertInlinePicture s svg

    selOoxml <- getSelectionOoxml c s

    logDimensions w h

    -- replace the size of the Word generated values with the
    -- newly calculated values
    replaceOoxml s (replaceSvgAndSize selOoxml svg w h)
    newInserted

  insertImage : (svg : String) -> (w,h : EMU) -> Act ()
  insertImage svg w h =
    use1 wordContext $ \c => Prelude.do
      insertingImage
      -- replace the selected svg (or the first in the selection)
      -- with the updated structure and adjust the size accordingly
      -- if an svg is selected
      -- if the selection is empty or does not include an svg,
      -- insert the new structure after the selection / cursor
      s <- getSelection c

      -- if the selection is empty, insert the svg as a new image
      False <- isEmpty s | True => insertNew c s svg w h

      -- load the selection as xml
      ooxml <- getSelectionOoxml c s

      -- check if only one CyBy-Draw generated image is selected
      checkSingleSelection ooxml

      -- replace the first occurring svg with the updated one
      -- and replace the new sizes
      replaceOoxml s (replaceSvgAndSize ooxml svg w h)
      imageReplaced

  toWord : DrawSettings => DrawState -> Act ()
  toWord s =
    -- throw an error if the canvas is empty
    if s.mol == G 0 empty
       then throw emptyMol
       else do
         timeStampUTC <- liftIO $ clockTime UTC
         let ts            := toNano timeStampUTC
         let (SD w h, svg) := exportSVGPair True ("timestamp: \{show ts}") s
         insertImage svg (cast w) (cast h)

  export
  fromWord : Logger JS => Act CDGraph
  fromWord =
    use1 wordContext $ \c => Prelude.do
      loadingImage
    
      s <- getSelection c
      False <- isEmpty s | True => throw emptySel
    
      -- load the whole selection as xml
      ooxml <- getSelectionOoxml c s
    
      -- check if only one CyBy-Draw generated image is selected
      checkSingleSelection ooxml
    
      -- extracting the MOL file directly from the xml structure
      -- of the current selection
      -- if there are several cyby-draw generated structures, the
      -- first in the selection is imported
      case extractMol ooxml of
        Nothing => throw noMolfile
        Just bs => case readMolfileE (toString bs) of
          Left e  => throw $ loadErr e
          Right m => molLoaded $> m

  wordButtons : DrawEnv => DrawState -> HTMLNodes
  wordButtons @{DE pre} s =
    [ cybyDrawBtn fromWord SVGimp []
    , expBtn @{DE pre} toWord s
    ]

  export
  WordExt : Extension
  WordExt =
    E
      { doExport     = toWord
      , buttons      = \_ => pure . wordButtons
      , adjust       = \_,_,s => disableExport s
      }
